apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resource/helmRepo.yaml
  - resource/helmRelease.yaml
  - resource/secret.yaml
  - resource/kyverno-flux-roles.yaml
configMapGenerator:
  - name: kyverno-helm-values
    files:
      - values.yaml=value-dev.yaml
configurations:
  - resource/kustomizeconfig.yaml
