apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-chart-release
  namespace: flux-system
spec:
  interval: 10m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno-helm-repo
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-helm-values