apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - resources/helmRepo.yaml
  - resources/helmRelease.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
configurations:
  - resources/kustomizeconfig.yaml