apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.16.1
      namespace: kube-system
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values